test node bin location

diff --git a/linux.yml b/linux.yml
--- a/linux.yml
+++ b/linux.yml
@@ -44,6 +44,12 @@ install:
           # check for node
           NODE_CHECK=$(type -P node)
 
+          echo ">>>>>>>>>>>>>>>>>>>>> $NODE_CHECK"
+
+          NODE_BIN=$(which node)
+
+          echo $($NODE_BIN -v)
+
           if [ -z NODE_CHECK ]; then
             echo "Nodejs not found. $error_msg";
             exit 1;
@@ -64,6 +70,18 @@ install:
               echo "yarn not found. $error_msg";
               exit 1;
             fi
+          fi
+
+          NODE_VERSION=$(node -v)
+
+          # get node major version
+          [[ $NODE_VERSION =~ ^v([0-9]+)\.[0-9]+\.[0-9]+ ]] && major_version=${BASH_REMATCH[1]}
+
+          if [[ "$major_version" -lt $minNodeVersion || "$major_version" -gt $maxNodeVersion ]]; then
+            echo "$NODE_VERSION is not supported by the New Relic Node.js Agent."
+            echo "$error_msg"
+
+            exit 1
           fi
 
           # initialize pid array
