update type -P check logic

diff --git a/linux.yml b/linux.yml
--- a/linux.yml
+++ b/linux.yml
@@ -41,6 +41,31 @@ install:
 
           check_yarn=0
 
+          # check for node
+          NODE_CHECK=$(type -P node)
+
+          if [ -z NODE_CHECK ] {
+            echo "Nodejs not found. $error_msg";
+            exit 1;
+          }
+
+          # check for npm
+          NPM_CHECK=$(type -P npm)
+
+          if [ -z NPM_CHECK ] {
+            echo "npm not found. Checking for yarn.";
+            check_yarn=1;
+          }
+
+          # check for yarn
+          if [ $check_yarn -eq 1 ]; then
+            YARN_CHECK=$(type -P yarn)
+            if [ -z YARN_CHECK ] {
+              echo "yarn not found. $error_msg";
+              exit 1;
+            }
+          fi
+
           # initialize pid array
           pid_array=()
 
